
spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /api/@api.version@

---
spring:
  config:
      activate:
        on-profile: dev

  datasource:
    url: jdbc:h2:mem:who_am_i
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
     enabled: true
     change-log: classpath:db/changelog/changelog-root.xml
